import type { Edge } from 'shared';
import { EdgeType, EdgeDirection } from 'shared';

export const seedEdges: Edge[] = [
    // ═══════════════════════════════════════════════════════════════════
    // FAMILY EDGES
    // ═══════════════════════════════════════════════════════════════════
    {
        id: 'e-bucky-anne-spouse',
        sourceId: 'bucky-fuller',
        targetId: 'anne-hewlett-fuller',
        edgeType: EdgeType.SPOUSE_OF,
        direction: EdgeDirection.BIDIRECTIONAL,
        startDate: '1917',
        endDate: '1983',
        strength: 1.0,
        confidence: 0.97,
        description: 'Married in 1917 and remained married until both died in 1983, within 36 hours of each other. Anne was a constant companion and supporter throughout Fuller\'s career.',
        tags: ['family'],
    },
    {
        id: 'e-bucky-allegra-parent',
        sourceId: 'bucky-fuller',
        targetId: 'allegra-fuller-snyder',
        edgeType: EdgeType.PARENT_OF,
        direction: EdgeDirection.DIRECTED,
        startDate: '1927',
        strength: 1.0,
        confidence: 0.95,
        description: 'Allegra was the surviving daughter of Bucky and Anne Fuller, born in 1927.',
        tags: ['family'],
    },
    {
        id: 'e-anne-allegra-parent',
        sourceId: 'anne-hewlett-fuller',
        targetId: 'allegra-fuller-snyder',
        edgeType: EdgeType.PARENT_OF,
        direction: EdgeDirection.DIRECTED,
        startDate: '1927',
        strength: 1.0,
        confidence: 0.95,
        description: 'Allegra was the daughter of Anne Hewlett Fuller.',
        tags: ['family'],
    },
    {
        id: 'e-allegra-jaime-parent',
        sourceId: 'allegra-fuller-snyder',
        targetId: 'jaime-snyder',
        edgeType: EdgeType.PARENT_OF,
        direction: EdgeDirection.DIRECTED,
        startDate: '1958',
        strength: 1.0,
        confidence: 0.90,
        description: 'Jaime Snyder is the son of Allegra Fuller Snyder and grandson of Buckminster Fuller.',
        tags: ['family'],
    },

    // ═══════════════════════════════════════════════════════════════════
    // COLLABORATIONS
    // ═══════════════════════════════════════════════════════════════════
    {
        id: 'e-bucky-sadao-collab',
        sourceId: 'bucky-fuller',
        targetId: 'shoji-sadao',
        edgeType: EdgeType.COLLABORATED_WITH,
        direction: EdgeDirection.BIDIRECTIONAL,
        startDate: '1954',
        endDate: '1983',
        strength: 0.95,
        confidence: 0.92,
        description: 'Sadao was Fuller\'s chief architectural collaborator for nearly 30 years. Together they designed the Montreal Biosphère (Expo 67), the Union Tank Car dome, and numerous other geodesic structures. They co-founded Fuller & Sadao Inc. in 1964.',
        tags: ['geodesic dome', 'architecture', 'Expo 67'],
    },
    {
        id: 'e-bucky-sadao-mentor',
        sourceId: 'bucky-fuller',
        targetId: 'shoji-sadao',
        edgeType: EdgeType.MENTORED,
        direction: EdgeDirection.DIRECTED,
        startDate: '1954',
        strength: 0.85,
        confidence: 0.85,
        description: 'Fuller mentored Sadao in geodesic engineering and systems thinking.',
        tags: ['mentorship', 'architecture'],
    },
    {
        id: 'e-bucky-anne-collab',
        sourceId: 'bucky-fuller',
        targetId: 'anne-hewlett-fuller',
        edgeType: EdgeType.COLLABORATED_WITH,
        direction: EdgeDirection.BIDIRECTIONAL,
        startDate: '1917',
        endDate: '1983',
        strength: 0.6,
        confidence: 0.75,
        description: 'Anne supported and collaborated on many of Fuller\'s projects throughout their marriage.',
        tags: ['family', 'collaboration'],
    },
    {
        id: 'e-bucky-snelson-collab',
        sourceId: 'bucky-fuller',
        targetId: 'kenneth-snelson',
        edgeType: EdgeType.COLLABORATED_WITH,
        direction: EdgeDirection.BIDIRECTIONAL,
        startDate: '1948',
        endDate: '1949',
        strength: 0.8,
        confidence: 0.88,
        description: 'Fuller and Snelson collaborated on the development of tensegrity structures at Black Mountain College. Snelson created the first tensegrity sculpture under Fuller\'s influence, though the attribution of the concept remained disputed between them.',
        tags: ['tensegrity', 'Black Mountain College'],
    },
    {
        id: 'e-bucky-snelson-taught',
        sourceId: 'bucky-fuller',
        targetId: 'kenneth-snelson',
        edgeType: EdgeType.TAUGHT,
        direction: EdgeDirection.DIRECTED,
        startDate: '1948',
        endDate: '1949',
        strength: 0.9,
        confidence: 0.90,
        description: 'Snelson was Fuller\'s student at Black Mountain College in 1948, during Fuller\'s celebrated summer sessions.',
        tags: ['Black Mountain College', 'education'],
    },
    {
        id: 'e-bucky-noguchi-collab',
        sourceId: 'bucky-fuller',
        targetId: 'isamu-noguchi',
        edgeType: EdgeType.COLLABORATED_WITH,
        direction: EdgeDirection.BIDIRECTIONAL,
        startDate: '1929',
        endDate: '1945',
        strength: 0.7,
        confidence: 0.82,
        description: 'Fuller and Noguchi collaborated on several projects including work on the Dymaxion car and other designs. They shared interests in sculpture, geometry, and design innovation.',
        tags: ['Dymaxion', 'design', 'sculpture'],
    },
    {
        id: 'e-bucky-noguchi-corresp',
        sourceId: 'bucky-fuller',
        targetId: 'isamu-noguchi',
        edgeType: EdgeType.CORRESPONDED_WITH,
        direction: EdgeDirection.BIDIRECTIONAL,
        startDate: '1929',
        endDate: '1983',
        strength: 0.6,
        confidence: 0.78,
        description: 'Fuller and Noguchi maintained a correspondence spanning several decades.',
        tags: ['correspondence'],
    },
    {
        id: 'e-bucky-ward-collab',
        sourceId: 'bucky-fuller',
        targetId: 'barbara-ward',
        edgeType: EdgeType.COLLABORATED_WITH,
        direction: EdgeDirection.BIDIRECTIONAL,
        startDate: '1965',
        endDate: '1975',
        strength: 0.7,
        confidence: 0.78,
        description: 'Fuller and Ward collaborated on global resource distribution models through the World Game project. Ward\'s focus on international development complemented Fuller\'s vision of comprehensive anticipatory design science.',
        tags: ['World Game', 'sustainability', 'global resources'],
    },
    {
        id: 'e-bucky-gabel-collab',
        sourceId: 'bucky-fuller',
        targetId: 'medard-gabel',
        edgeType: EdgeType.COLLABORATED_WITH,
        direction: EdgeDirection.BIDIRECTIONAL,
        startDate: '1971',
        endDate: '1983',
        strength: 0.9,
        confidence: 0.85,
        description: 'Gabel was one of Fuller\'s closest collaborators on the World Game, helping to develop and run the simulation workshop that modeled global resource allocation.',
        tags: ['World Game', 'systems thinking'],
    },
    {
        id: 'e-bucky-gabel-taught',
        sourceId: 'bucky-fuller',
        targetId: 'medard-gabel',
        edgeType: EdgeType.TAUGHT,
        direction: EdgeDirection.DIRECTED,
        startDate: '1968',
        strength: 0.85,
        confidence: 0.82,
        description: 'Gabel was Fuller\'s student before becoming his closest collaborator on the World Game.',
        tags: ['education', 'World Game'],
    },
    {
        id: 'e-bucky-applewhite-collab',
        sourceId: 'bucky-fuller',
        targetId: 'ej-applewhite',
        edgeType: EdgeType.COLLABORATED_WITH,
        direction: EdgeDirection.BIDIRECTIONAL,
        startDate: '1966',
        endDate: '1979',
        strength: 0.9,
        confidence: 0.90,
        description: 'Applewhite was Fuller\'s chief literary collaborator and co-author of "Synergetics" (1975) and "Synergetics 2" (1979). He helped organize and elucidate Fuller\'s complex geometric philosophy.',
        tags: ['Synergetics', 'writing', 'collaboration'],
    },
    {
        id: 'e-bucky-applewhite-corresp',
        sourceId: 'bucky-fuller',
        targetId: 'ej-applewhite',
        edgeType: EdgeType.CORRESPONDED_WITH,
        direction: EdgeDirection.BIDIRECTIONAL,
        startDate: '1960',
        endDate: '1983',
        strength: 0.8,
        confidence: 0.85,
        description: 'Extensive correspondence related to the Synergetics project.',
        tags: ['Synergetics', 'correspondence'],
    },

    // ═══════════════════════════════════════════════════════════════════
    // INFLUENCE & EPISTEMIC EDGES
    // ═══════════════════════════════════════════════════════════════════
    {
        id: 'e-bucky-mcluhan-corresp',
        sourceId: 'bucky-fuller',
        targetId: 'marshall-mcluhan',
        edgeType: EdgeType.CORRESPONDED_WITH,
        direction: EdgeDirection.BIDIRECTIONAL,
        startDate: '1960',
        endDate: '1980',
        strength: 0.7,
        confidence: 0.85,
        description: 'Fuller and McLuhan maintained an active correspondence throughout the 1960s and 1970s, exchanging ideas about technology, media, and global connectivity.',
        tags: ['media theory', 'technology', 'correspondence'],
    },
    {
        id: 'e-bucky-mcluhan-influence',
        sourceId: 'marshall-mcluhan',
        targetId: 'bucky-fuller',
        edgeType: EdgeType.INFLUENCED_BY,
        direction: EdgeDirection.DIRECTED,
        startDate: '1960',
        strength: 0.65,
        confidence: 0.80,
        description: 'Fuller and McLuhan mutually influenced each other. Fuller\'s concept of "Spaceship Earth" resonated with McLuhan\'s "global village" — both envisioned technology creating planetary interconnection.',
        tags: ['influence', 'media theory', 'global village'],
    },
    {
        id: 'e-brand-bucky-influence',
        sourceId: 'stewart-brand',
        targetId: 'bucky-fuller',
        edgeType: EdgeType.INFLUENCED_BY,
        direction: EdgeDirection.DIRECTED,
        startDate: '1966',
        strength: 0.9,
        confidence: 0.92,
        description: 'Brand was profoundly influenced by Fuller. The Whole Earth Catalog was directly inspired by Fuller\'s concept of comprehensive information access. Brand campaigned for the first whole-Earth photograph partly inspired by Fuller\'s "Spaceship Earth" metaphor.',
        tags: ['Whole Earth Catalog', 'influence', 'Spaceship Earth'],
    },
    {
        id: 'e-brand-bucky-corresp',
        sourceId: 'stewart-brand',
        targetId: 'bucky-fuller',
        edgeType: EdgeType.CORRESPONDED_WITH,
        direction: EdgeDirection.BIDIRECTIONAL,
        startDate: '1966',
        endDate: '1983',
        strength: 0.7,
        confidence: 0.85,
        description: 'Brand corresponded with Fuller throughout the 1960s and 1970s.',
        tags: ['correspondence', 'counterculture'],
    },
    {
        id: 'e-brand-bucky-cited',
        sourceId: 'stewart-brand',
        targetId: 'bucky-fuller',
        edgeType: EdgeType.CITED,
        direction: EdgeDirection.DIRECTED,
        startDate: '1968',
        strength: 0.85,
        confidence: 0.95,
        description: 'Brand frequently cited Fuller in the Whole Earth Catalog and in his other writings. The subtitle of the first Whole Earth Catalog ("access to tools") echoes Fuller\'s design philosophy.',
        tags: ['citation', 'Whole Earth Catalog'],
    },
    {
        id: 'e-bucky-wiener-knewof',
        sourceId: 'bucky-fuller',
        targetId: 'norbert-wiener',
        edgeType: EdgeType.KNEW_OF,
        direction: EdgeDirection.DIRECTED,
        startDate: '1948',
        strength: 0.6,
        confidence: 0.78,
        description: 'Fuller was aware of and interested in Wiener\'s cybernetics work, which resonated with Fuller\'s own systems thinking approach.',
        tags: ['cybernetics', 'systems theory'],
    },
    {
        id: 'e-bucky-wiener-readwork',
        sourceId: 'bucky-fuller',
        targetId: 'norbert-wiener',
        edgeType: EdgeType.READ_WORK_OF,
        direction: EdgeDirection.DIRECTED,
        startDate: '1948',
        strength: 0.7,
        confidence: 0.75,
        description: 'Fuller read Wiener\'s "Cybernetics" (1948) and other works.',
        tags: ['cybernetics', 'reading'],
    },
    {
        id: 'e-bucky-wiener-cited',
        sourceId: 'bucky-fuller',
        targetId: 'norbert-wiener',
        edgeType: EdgeType.CITED,
        direction: EdgeDirection.DIRECTED,
        startDate: '1962',
        strength: 0.5,
        confidence: 0.70,
        description: 'Fuller cited Wiener\'s cybernetics concepts in his own work.',
        tags: ['cybernetics', 'citation'],
    },
    {
        id: 'e-bucky-einstein-met',
        sourceId: 'bucky-fuller',
        targetId: 'albert-einstein',
        edgeType: EdgeType.MET_IN_PERSON,
        direction: EdgeDirection.BIDIRECTIONAL,
        startDate: '1935',
        strength: 0.5,
        confidence: 0.65,
        description: 'Fuller reportedly met Einstein in the 1930s. The details of their meeting are not extensively documented, but Fuller referenced it in later writings.',
        tags: ['meeting', 'physics'],
    },
    {
        id: 'e-bucky-einstein-knewof',
        sourceId: 'bucky-fuller',
        targetId: 'albert-einstein',
        edgeType: EdgeType.KNEW_OF,
        direction: EdgeDirection.DIRECTED,
        startDate: '1920',
        strength: 0.9,
        confidence: 0.95,
        description: 'Fuller was deeply aware of Einstein\'s work and frequently referenced relativity and curved space in his own thinking about geometry and structure.',
        tags: ['physics', 'geometry', 'influence'],
    },
    {
        id: 'e-ward-bucky-influence',
        sourceId: 'barbara-ward',
        targetId: 'bucky-fuller',
        edgeType: EdgeType.INFLUENCED_BY,
        direction: EdgeDirection.DIRECTED,
        startDate: '1965',
        strength: 0.6,
        confidence: 0.72,
        description: 'Ward was influenced by Fuller\'s global systems thinking and resource distribution models.',
        tags: ['influence', 'sustainability'],
    },
    {
        id: 'e-edmondson-bucky-readwork',
        sourceId: 'amy-edmondson',
        targetId: 'bucky-fuller',
        edgeType: EdgeType.READ_WORK_OF,
        direction: EdgeDirection.DIRECTED,
        startDate: '1980',
        strength: 0.95,
        confidence: 0.92,
        description: 'Edmondson deeply studied Fuller\'s synergetic geometry, resulting in her book "A Fuller Explanation" (1987), one of the most accessible introductions to his ideas.',
        tags: ['synergetics', 'reading', 'education'],
    },
    {
        id: 'e-edmondson-bucky-student',
        sourceId: 'amy-edmondson',
        targetId: 'bucky-fuller',
        edgeType: EdgeType.STUDENT_OF,
        direction: EdgeDirection.DIRECTED,
        startDate: '1980',
        endDate: '1983',
        strength: 0.8,
        confidence: 0.82,
        description: 'Edmondson worked as Fuller\'s chief engineer and studied his geometric philosophy directly.',
        tags: ['synergetics', 'engineering'],
    },
    {
        id: 'e-bucky-ehrlich-corresp',
        sourceId: 'bucky-fuller',
        targetId: 'paul-ehrlich',
        edgeType: EdgeType.CORRESPONDED_WITH,
        direction: EdgeDirection.BIDIRECTIONAL,
        startDate: '1968',
        endDate: '1980',
        strength: 0.5,
        confidence: 0.70,
        description: 'Fuller and Ehrlich corresponded about ecology, population, and global resource management. Their perspectives diverged — Ehrlich was more pessimistic about population limits while Fuller believed technology could raise global living standards.',
        tags: ['ecology', 'population', 'correspondence'],
    },
    {
        id: 'e-bucky-ehrlich-cited',
        sourceId: 'paul-ehrlich',
        targetId: 'bucky-fuller',
        edgeType: EdgeType.CITED,
        direction: EdgeDirection.DIRECTED,
        startDate: '1969',
        strength: 0.4,
        confidence: 0.65,
        description: 'Ehrlich cited Fuller in discussions of global ecology and resource management.',
        tags: ['ecology', 'citation'],
    },

    // ═══════════════════════════════════════════════════════════════════
    // CONTEMPORANEOUS & SPATIAL EDGES
    // ═══════════════════════════════════════════════════════════════════
    {
        id: 'e-bucky-cage-contemp',
        sourceId: 'bucky-fuller',
        targetId: 'john-cage',
        edgeType: EdgeType.CONTEMPORANEOUS_AT,
        direction: EdgeDirection.BIDIRECTIONAL,
        startDate: '1948',
        endDate: '1949',
        strength: 0.7,
        confidence: 0.90,
        description: 'Both were at Black Mountain College in the summer of 1948, during the legendary summer session that included Cage\'s first "event" performance and Fuller\'s geodesic dome experiments.',
        tags: ['Black Mountain College', '1948'],
    },
    {
        id: 'e-cage-bucky-influence',
        sourceId: 'john-cage',
        targetId: 'bucky-fuller',
        edgeType: EdgeType.INFLUENCED_BY,
        direction: EdgeDirection.DIRECTED,
        startDate: '1948',
        strength: 0.6,
        confidence: 0.75,
        description: 'Cage was influenced by Fuller\'s holistic systems approach. Fuller\'s geometric and structural thinking informed Cage\'s own explorations of chance operations and environmental composition.',
        tags: ['influence', 'Black Mountain College'],
    },
    {
        id: 'e-bucky-cunningham-contemp',
        sourceId: 'bucky-fuller',
        targetId: 'merce-cunningham',
        edgeType: EdgeType.CONTEMPORANEOUS_AT,
        direction: EdgeDirection.BIDIRECTIONAL,
        startDate: '1948',
        endDate: '1949',
        strength: 0.5,
        confidence: 0.85,
        description: 'Both were present at Black Mountain College during the 1948 summer session.',
        tags: ['Black Mountain College', '1948'],
    },
    {
        id: 'e-bucky-cunningham-knewof',
        sourceId: 'bucky-fuller',
        targetId: 'merce-cunningham',
        edgeType: EdgeType.KNEW_OF,
        direction: EdgeDirection.DIRECTED,
        startDate: '1948',
        strength: 0.4,
        confidence: 0.75,
        description: 'Fuller was aware of Cunningham\'s work in dance, both being part of the Black Mountain College community.',
        tags: ['Black Mountain College', 'dance'],
    },
    {
        id: 'e-bucky-gropius-contemp',
        sourceId: 'bucky-fuller',
        targetId: 'walter-gropius',
        edgeType: EdgeType.CONTEMPORANEOUS_AT,
        direction: EdgeDirection.BIDIRECTIONAL,
        startDate: '1948',
        endDate: '1949',
        strength: 0.5,
        confidence: 0.85,
        description: 'Both were at Harvard during Fuller\'s 1948–49 period there, though Gropius was chairman of the architecture department and Fuller was an invited outsider.',
        tags: ['Harvard', 'architecture'],
    },
    {
        id: 'e-bucky-gropius-opposed',
        sourceId: 'bucky-fuller',
        targetId: 'walter-gropius',
        edgeType: EdgeType.OPPOSED,
        direction: EdgeDirection.BIDIRECTIONAL,
        startDate: '1948',
        endDate: '1952',
        strength: 0.7,
        confidence: 0.80,
        description: 'Fuller and Gropius had a well-documented intellectual opposition. Gropius represented the architectural establishment; Fuller was the radical outsider. Their disagreements about the role of industrialization in architecture were significant.',
        tags: ['opposition', 'architecture', 'Harvard'],
    },
    {
        id: 'e-bucky-albers-contemp',
        sourceId: 'bucky-fuller',
        targetId: 'josef-albers',
        edgeType: EdgeType.CONTEMPORANEOUS_AT,
        direction: EdgeDirection.BIDIRECTIONAL,
        startDate: '1948',
        endDate: '1949',
        strength: 0.6,
        confidence: 0.88,
        description: 'Both were at Black Mountain College. Albers was a permanent faculty member; Fuller was invited for the legendary 1948 summer session.',
        tags: ['Black Mountain College'],
    },
    {
        id: 'e-bucky-albers-knewof',
        sourceId: 'bucky-fuller',
        targetId: 'josef-albers',
        edgeType: EdgeType.KNEW_OF,
        direction: EdgeDirection.DIRECTED,
        startDate: '1948',
        strength: 0.5,
        confidence: 0.82,
        description: 'Fuller knew of Albers through their shared time at Black Mountain College.',
        tags: ['Black Mountain College'],
    },
    {
        id: 'e-cage-cunningham-collab',
        sourceId: 'john-cage',
        targetId: 'merce-cunningham',
        edgeType: EdgeType.COLLABORATED_WITH,
        direction: EdgeDirection.BIDIRECTIONAL,
        startDate: '1942',
        endDate: '1992',
        strength: 1.0,
        confidence: 0.97,
        description: 'Cage and Cunningham were life partners and artistic collaborators for nearly 50 years. Their collaboration — Cage composing music independently of Cunningham\'s choreography — revolutionized both fields.',
        tags: ['music', 'dance', 'collaboration'],
    },
    {
        id: 'e-cage-cunningham-spouse',
        sourceId: 'john-cage',
        targetId: 'merce-cunningham',
        edgeType: EdgeType.SPOUSE_OF,
        direction: EdgeDirection.BIDIRECTIONAL,
        startDate: '1942',
        endDate: '1992',
        strength: 1.0,
        confidence: 0.95,
        description: 'Cage and Cunningham were romantic and creative partners for 50 years.',
        tags: ['family'],
    },
    {
        id: 'e-albers-snelson-taught',
        sourceId: 'josef-albers',
        targetId: 'kenneth-snelson',
        edgeType: EdgeType.TAUGHT,
        direction: EdgeDirection.DIRECTED,
        startDate: '1948',
        endDate: '1949',
        strength: 0.6,
        confidence: 0.80,
        description: 'Snelson studied under both Albers and Fuller at Black Mountain College.',
        tags: ['Black Mountain College', 'education'],
    },
];
