import type { Person } from 'shared';
import { DatePrecision } from 'shared';

export const seedPersons: Person[] = [
    {
        id: 'bucky-fuller',
        canonicalName: 'R. Buckminster Fuller',
        alternateNames: ['Bucky', 'Richard Buckminster Fuller'],
        birthDate: '1895-07-12',
        birthDatePrecision: DatePrecision.DAY,
        birthPlace: { city: 'Milton', region: 'Massachusetts', country: 'USA', lat: 42.25, lng: -71.07 },
        deathDate: '1983-07-01',
        deathDatePrecision: DatePrecision.DAY,
        deathPlace: { city: 'Los Angeles', region: 'California', country: 'USA', lat: 34.05, lng: -118.24 },
        gender: 'Male',
        nationalities: [{ name: 'American' }],
        occupations: [
            { name: 'Architect', domain: 'architecture' },
            { name: 'Systems Theorist', domain: 'systems-theory' },
            { name: 'Inventor', domain: 'engineering' },
            { name: 'Futurist', domain: 'futurism' },
            { name: 'Author', domain: 'writing' },
        ],
        affiliations: [
            { name: 'Black Mountain College', role: 'Visiting Lecturer', start: '1948', end: '1949' },
            { name: 'Southern Illinois University', role: 'Research Professor', start: '1959', end: '1970' },
            { name: 'Harvard University', role: 'Charles Eliot Norton Professor', start: '1961', end: '1962' },
            { name: 'Buckminster Fuller Institute', role: 'Founder' },
        ],
        bioSummary: 'Richard Buckminster "Bucky" Fuller was an American architect, systems theorist, designer, inventor, philosopher, and futurist. He developed numerous inventions, mainly architectural designs including the geodesic dome, and popularized concepts like "Spaceship Earth" and synergetics. A prolific thinker who held 28 patents and authored 30 books, Fuller was one of the most original thinkers of the twentieth century.',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/BuckminsterFuller1.jpg/440px-BuckminsterFuller1.jpg',
        wikidataId: 'Q102289',
        wikipediaSlug: 'Buckminster_Fuller',
        confidence: 0.97,
        tags: ['geodesic dome', 'synergetics', 'systems thinking', 'Spaceship Earth', 'Dymaxion', 'tensegrity'],
        primaryDomain: 'architecture',
    },
    {
        id: 'anne-hewlett-fuller',
        canonicalName: 'Anne Hewlett Fuller',
        birthDate: '1896',
        birthDatePrecision: DatePrecision.YEAR,
        birthPlace: { country: 'USA' },
        deathDate: '1983',
        deathDatePrecision: DatePrecision.YEAR,
        gender: 'Female',
        nationalities: [{ name: 'American' }],
        occupations: [{ name: 'Artist', domain: 'art' }],
        bioSummary: 'Anne Hewlett Fuller was an American artist and the wife of R. Buckminster Fuller for 66 years. She was the daughter of James Monroe Hewlett, a noted architect and muralist. She was a constant supporter and collaborator in Fuller\'s work throughout their long life together.',
        confidence: 0.85,
        tags: ['family', 'art'],
        primaryDomain: 'family',
    },
    {
        id: 'shoji-sadao',
        canonicalName: 'Shoji Sadao',
        birthDate: '1927',
        birthDatePrecision: DatePrecision.YEAR,
        birthPlace: { city: 'Los Angeles', region: 'California', country: 'USA' },
        deathDate: '2019',
        deathDatePrecision: DatePrecision.YEAR,
        gender: 'Male',
        nationalities: [{ name: 'American' }],
        occupations: [
            { name: 'Architect', domain: 'architecture' },
            { name: 'Engineer', domain: 'engineering' },
        ],
        affiliations: [
            { name: 'Fuller & Sadao Inc.', role: 'Partner', start: '1964' },
            { name: 'Buckminster Fuller Institute', role: 'Director' },
        ],
        bioSummary: 'Shoji Sadao was an American architect and engineer who was one of Buckminster Fuller\'s closest collaborators. Together they designed many geodesic structures, including the iconic Montreal Biosphère for Expo 67. He co-founded Fuller & Sadao Inc. and later served as director of the Buckminster Fuller Institute.',
        wikidataId: 'Q7501437',
        confidence: 0.82,
        tags: ['geodesic dome', 'architecture', 'Expo 67'],
        primaryDomain: 'architecture',
    },
    {
        id: 'john-cage',
        canonicalName: 'John Cage',
        birthDate: '1912-09-05',
        birthDatePrecision: DatePrecision.DAY,
        birthPlace: { city: 'Los Angeles', region: 'California', country: 'USA' },
        deathDate: '1992-08-12',
        deathDatePrecision: DatePrecision.DAY,
        deathPlace: { city: 'New York City', region: 'New York', country: 'USA' },
        gender: 'Male',
        nationalities: [{ name: 'American' }],
        occupations: [
            { name: 'Composer', domain: 'music' },
            { name: 'Music Theorist', domain: 'music' },
            { name: 'Artist', domain: 'art' },
        ],
        affiliations: [
            { name: 'Black Mountain College', role: 'Faculty', start: '1948', end: '1953' },
            { name: 'New School for Social Research', role: 'Faculty', start: '1956', end: '1960' },
        ],
        bioSummary: 'John Cage was an American composer, music theorist, artist, and philosopher. A pioneer of indeterminacy in music and the use of non-standard instruments, Cage was one of the leading figures of the post-war avant-garde. His composition 4\'33" challenged conventional definitions of music.',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/John_Cage_%281988%29.jpg/440px-John_Cage_%281988%29.jpg',
        wikidataId: 'Q180727',
        wikipediaSlug: 'John_Cage',
        confidence: 0.95,
        tags: ['avant-garde', 'experimental music', 'Black Mountain College', 'indeterminacy'],
        primaryDomain: 'music',
    },
    {
        id: 'merce-cunningham',
        canonicalName: 'Merce Cunningham',
        birthDate: '1919-04-16',
        birthDatePrecision: DatePrecision.DAY,
        birthPlace: { city: 'Centralia', region: 'Washington', country: 'USA' },
        deathDate: '2009-07-26',
        deathDatePrecision: DatePrecision.DAY,
        deathPlace: { city: 'New York City', region: 'New York', country: 'USA' },
        gender: 'Male',
        nationalities: [{ name: 'American' }],
        occupations: [
            { name: 'Dancer', domain: 'dance' },
            { name: 'Choreographer', domain: 'dance' },
        ],
        affiliations: [
            { name: 'Black Mountain College', role: 'Artist', start: '1948', end: '1953' },
            { name: 'Merce Cunningham Dance Company', role: 'Founder', start: '1953' },
        ],
        bioSummary: 'Merce Cunningham was an American dancer and choreographer at the forefront of modern dance for more than 50 years. He frequently collaborated with John Cage, his life partner, and with visual artists including Robert Rauschenberg and Jasper Johns.',
        wikidataId: 'Q309640',
        wikipediaSlug: 'Merce_Cunningham',
        confidence: 0.92,
        tags: ['modern dance', 'Black Mountain College', 'choreography'],
        primaryDomain: 'dance',
    },
    {
        id: 'kenneth-snelson',
        canonicalName: 'Kenneth Snelson',
        birthDate: '1927-06-29',
        birthDatePrecision: DatePrecision.DAY,
        birthPlace: { city: 'Pendleton', region: 'Oregon', country: 'USA' },
        deathDate: '2016-12-22',
        deathDatePrecision: DatePrecision.DAY,
        deathPlace: { city: 'New York City', region: 'New York', country: 'USA' },
        gender: 'Male',
        nationalities: [{ name: 'American' }],
        occupations: [
            { name: 'Sculptor', domain: 'art' },
            { name: 'Photographer', domain: 'art' },
        ],
        affiliations: [
            { name: 'Black Mountain College', role: 'Student', start: '1948', end: '1949' },
        ],
        bioSummary: 'Kenneth Snelson was an American sculptor and photographer best known for his tensegrity sculptures — structures of rigid struts suspended in a web of cables. His seminal work "Needle Tower" (1968) stands at the Hirshhorn Museum in Washington, D.C. He studied under Fuller and Josef Albers at Black Mountain College.',
        wikidataId: 'Q1739618',
        wikipediaSlug: 'Kenneth_Snelson',
        confidence: 0.88,
        tags: ['tensegrity', 'sculpture', 'Black Mountain College'],
        primaryDomain: 'art',
    },
    {
        id: 'isamu-noguchi',
        canonicalName: 'Isamu Noguchi',
        birthDate: '1904-11-17',
        birthDatePrecision: DatePrecision.DAY,
        birthPlace: { city: 'Los Angeles', region: 'California', country: 'USA' },
        deathDate: '1988-12-30',
        deathDatePrecision: DatePrecision.DAY,
        deathPlace: { city: 'New York City', region: 'New York', country: 'USA' },
        gender: 'Male',
        nationalities: [{ name: 'American' }, { name: 'Japanese' }],
        occupations: [
            { name: 'Sculptor', domain: 'art' },
            { name: 'Landscape Architect', domain: 'architecture' },
            { name: 'Designer', domain: 'design' },
        ],
        bioSummary: 'Isamu Noguchi was an American-Japanese artist and landscape architect known for his sculpture, public works, furniture, and lighting designs. He collaborated with Fuller on the Dymaxion Deployment Unit and other projects, bridging Eastern and Western design philosophies.',
        wikidataId: 'Q316284',
        wikipediaSlug: 'Isamu_Noguchi',
        confidence: 0.92,
        tags: ['sculpture', 'design', 'landscape architecture', 'Dymaxion'],
        primaryDomain: 'art',
    },
    {
        id: 'marshall-mcluhan',
        canonicalName: 'Marshall McLuhan',
        birthDate: '1911-07-21',
        birthDatePrecision: DatePrecision.DAY,
        birthPlace: { city: 'Edmonton', region: 'Alberta', country: 'Canada' },
        deathDate: '1980-12-31',
        deathDatePrecision: DatePrecision.DAY,
        deathPlace: { city: 'Toronto', region: 'Ontario', country: 'Canada' },
        gender: 'Male',
        nationalities: [{ name: 'Canadian' }],
        occupations: [
            { name: 'Media Theorist', domain: 'philosophy' },
            { name: 'Professor', domain: 'education' },
            { name: 'Author', domain: 'writing' },
        ],
        affiliations: [
            { name: 'University of Toronto', role: 'Professor', start: '1946', end: '1979' },
        ],
        bioSummary: 'Herbert Marshall McLuhan was a Canadian philosopher and media theorist whose work is a cornerstone of media studies. He coined phrases like "the medium is the message" and "global village." He corresponded with Fuller and they mutually influenced each other\'s thinking about technology and society.',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Marshall_McLuhan.jpg/440px-Marshall_McLuhan.jpg',
        wikidataId: 'Q34012',
        wikipediaSlug: 'Marshall_McLuhan',
        confidence: 0.95,
        tags: ['media theory', 'global village', 'communication'],
        primaryDomain: 'philosophy',
    },
    {
        id: 'stewart-brand',
        canonicalName: 'Stewart Brand',
        birthDate: '1938-12-14',
        birthDatePrecision: DatePrecision.DAY,
        birthPlace: { city: 'Rockford', region: 'Illinois', country: 'USA' },
        gender: 'Male',
        nationalities: [{ name: 'American' }],
        occupations: [
            { name: 'Writer', domain: 'writing' },
            { name: 'Editor', domain: 'journalism' },
            { name: 'Futurist', domain: 'futurism' },
        ],
        affiliations: [
            { name: 'Whole Earth Catalog', role: 'Founder/Editor', start: '1968', end: '1972' },
            { name: 'Long Now Foundation', role: 'Co-founder', start: '1996' },
            { name: 'Global Business Network', role: 'Co-founder', start: '1987' },
        ],
        bioSummary: 'Stewart Brand is an American writer, editor, and futurist best known for founding the Whole Earth Catalog (1968–1972). Deeply influenced by Fuller, he campaigned for NASA to release the first whole-Earth photograph. He went on to co-found the Long Now Foundation and the Global Business Network.',
        wikidataId: 'Q352835',
        wikipediaSlug: 'Stewart_Brand',
        confidence: 0.93,
        tags: ['Whole Earth Catalog', 'counterculture', 'Long Now', 'futurism'],
        primaryDomain: 'counterculture',
    },
    {
        id: 'allegra-fuller-snyder',
        canonicalName: 'Allegra Fuller Snyder',
        birthDate: '1927',
        birthDatePrecision: DatePrecision.YEAR,
        deathDate: '2017',
        deathDatePrecision: DatePrecision.YEAR,
        gender: 'Female',
        nationalities: [{ name: 'American' }],
        occupations: [
            { name: 'Dance Ethnologist', domain: 'dance' },
            { name: 'Professor', domain: 'education' },
        ],
        affiliations: [
            { name: 'UCLA', role: 'Professor of Dance Ethnology', start: '1966' },
        ],
        bioSummary: 'Allegra Fuller Snyder was the daughter of R. Buckminster Fuller and Anne Hewlett Fuller. She became a distinguished dance ethnologist and professor at UCLA, pioneering the field of dance notation and ethnographic documentation of movement.',
        confidence: 0.80,
        tags: ['family', 'dance', 'ethnology'],
        primaryDomain: 'dance',
    },
    {
        id: 'norbert-wiener',
        canonicalName: 'Norbert Wiener',
        birthDate: '1894-11-26',
        birthDatePrecision: DatePrecision.DAY,
        birthPlace: { city: 'Columbia', region: 'Missouri', country: 'USA' },
        deathDate: '1964-03-18',
        deathDatePrecision: DatePrecision.DAY,
        deathPlace: { city: 'Stockholm', country: 'Sweden' },
        gender: 'Male',
        nationalities: [{ name: 'American' }],
        occupations: [
            { name: 'Mathematician', domain: 'mathematics' },
            { name: 'Philosopher', domain: 'philosophy' },
        ],
        affiliations: [
            { name: 'Massachusetts Institute of Technology', role: 'Professor', start: '1919', end: '1964' },
        ],
        bioSummary: 'Norbert Wiener was an American mathematician and philosopher who is considered the originator of cybernetics. His book "Cybernetics: or Control and Communication in the Animal and the Machine" (1948) established the field that would profoundly influence computer science, systems theory, and Fuller\'s own thinking.',
        wikidataId: 'Q256477',
        wikipediaSlug: 'Norbert_Wiener',
        confidence: 0.95,
        tags: ['cybernetics', 'mathematics', 'systems theory', 'MIT'],
        primaryDomain: 'cybernetics',
    },
    {
        id: 'albert-einstein',
        canonicalName: 'Albert Einstein',
        birthDate: '1879-03-14',
        birthDatePrecision: DatePrecision.DAY,
        birthPlace: { city: 'Ulm', country: 'Germany' },
        deathDate: '1955-04-18',
        deathDatePrecision: DatePrecision.DAY,
        deathPlace: { city: 'Princeton', region: 'New Jersey', country: 'USA' },
        gender: 'Male',
        nationalities: [
            { name: 'German', start: '1879', end: '1896' },
            { name: 'Swiss', start: '1901' },
            { name: 'American', start: '1940' },
        ],
        occupations: [
            { name: 'Physicist', domain: 'science' },
            { name: 'Professor', domain: 'education' },
        ],
        affiliations: [
            { name: 'Institute for Advanced Study', role: 'Professor', start: '1933', end: '1955' },
            { name: 'ETH Zurich', role: 'Professor', start: '1912', end: '1914' },
        ],
        bioSummary: 'Albert Einstein was a German-born theoretical physicist who developed the theory of relativity, one of the two pillars of modern physics. He received the Nobel Prize in Physics in 1921. Fuller met Einstein in the 1930s and was deeply influenced by his geometric approach to physics.',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Albert_Einstein_Head.jpg/440px-Albert_Einstein_Head.jpg',
        wikidataId: 'Q937',
        wikipediaSlug: 'Albert_Einstein',
        confidence: 0.99,
        tags: ['physics', 'relativity', 'Nobel Prize'],
        primaryDomain: 'science',
    },
    {
        id: 'walter-gropius',
        canonicalName: 'Walter Gropius',
        birthDate: '1883-05-18',
        birthDatePrecision: DatePrecision.DAY,
        birthPlace: { city: 'Berlin', country: 'Germany' },
        deathDate: '1969-07-05',
        deathDatePrecision: DatePrecision.DAY,
        deathPlace: { city: 'Boston', region: 'Massachusetts', country: 'USA' },
        gender: 'Male',
        nationalities: [{ name: 'German' }, { name: 'American', start: '1944' }],
        occupations: [
            { name: 'Architect', domain: 'architecture' },
            { name: 'Professor', domain: 'education' },
        ],
        affiliations: [
            { name: 'Bauhaus', role: 'Founder/Director', start: '1919', end: '1928' },
            { name: 'Harvard Graduate School of Design', role: 'Chairman', start: '1937', end: '1952' },
        ],
        bioSummary: 'Walter Gropius was a German-American architect and founder of the Bauhaus School. While he and Fuller were contemporaneous at Harvard in 1948–49, their relationship was characterized by intellectual opposition — Gropius representing the established architectural academy and Fuller the radical outsider.',
        wikidataId: 'Q61071',
        wikipediaSlug: 'Walter_Gropius',
        confidence: 0.93,
        tags: ['Bauhaus', 'architecture', 'modernism', 'Harvard'],
        primaryDomain: 'architecture',
    },
    {
        id: 'josef-albers',
        canonicalName: 'Josef Albers',
        birthDate: '1888-03-19',
        birthDatePrecision: DatePrecision.DAY,
        birthPlace: { city: 'Bottrop', country: 'Germany' },
        deathDate: '1976-03-25',
        deathDatePrecision: DatePrecision.DAY,
        deathPlace: { city: 'New Haven', region: 'Connecticut', country: 'USA' },
        gender: 'Male',
        nationalities: [{ name: 'German' }, { name: 'American', start: '1939' }],
        occupations: [
            { name: 'Artist', domain: 'art' },
            { name: 'Educator', domain: 'education' },
        ],
        affiliations: [
            { name: 'Bauhaus', role: 'Faculty', start: '1925', end: '1933' },
            { name: 'Black Mountain College', role: 'Faculty', start: '1933', end: '1949' },
            { name: 'Yale University', role: 'Chairman, Department of Design', start: '1950', end: '1958' },
        ],
        bioSummary: 'Josef Albers was a German-born American artist and educator. After teaching at the Bauhaus, he joined Black Mountain College where his rigorous approach to color theory and design education influenced generations of artists. He was contemporaneous with Fuller at Black Mountain College.',
        wikidataId: 'Q170071',
        wikipediaSlug: 'Josef_Albers',
        confidence: 0.92,
        tags: ['Bauhaus', 'Black Mountain College', 'color theory', 'art education'],
        primaryDomain: 'art',
    },
    {
        id: 'barbara-ward',
        canonicalName: 'Barbara Ward',
        alternateNames: ['Baroness Jackson of Lodsworth'],
        birthDate: '1914-05-23',
        birthDatePrecision: DatePrecision.DAY,
        birthPlace: { city: 'York', country: 'United Kingdom' },
        deathDate: '1981-05-31',
        deathDatePrecision: DatePrecision.DAY,
        deathPlace: { city: 'Lodsworth', country: 'United Kingdom' },
        gender: 'Female',
        nationalities: [{ name: 'British' }],
        occupations: [
            { name: 'Economist', domain: 'policy' },
            { name: 'Author', domain: 'writing' },
        ],
        affiliations: [
            { name: 'The Economist', role: 'Foreign Editor', start: '1940', end: '1950' },
            { name: 'Columbia University', role: 'Albert Schweitzer Professor', start: '1968', end: '1973' },
        ],
        bioSummary: 'Barbara Ward, Baroness Jackson of Lodsworth, was a British economist, author, and internationalist. She collaborated with Fuller on global resource distribution models through the World Game project and was a pioneer of sustainable development thinking.',
        wikidataId: 'Q441665',
        wikipediaSlug: 'Barbara_Ward,_Baroness_Jackson_of_Lodsworth',
        confidence: 0.85,
        tags: ['economics', 'sustainability', 'World Game', 'policy'],
        primaryDomain: 'policy',
    },
    {
        id: 'medard-gabel',
        canonicalName: 'Medard Gabel',
        birthDate: '1943',
        birthDatePrecision: DatePrecision.YEAR,
        gender: 'Male',
        nationalities: [{ name: 'American' }],
        occupations: [
            { name: 'Designer', domain: 'design' },
            { name: 'Author', domain: 'writing' },
            { name: 'Educator', domain: 'education' },
        ],
        affiliations: [
            { name: 'World Game Institute', role: 'Executive Director', start: '1972' },
            { name: 'BigPicture SmallWorld', role: 'Founder' },
        ],
        bioSummary: 'Medard Gabel is a designer, educator, and author who was one of Fuller\'s most dedicated students and closest collaborators. He co-developed the World Game with Fuller and has continued to extend Fuller\'s global resource modeling work through the World Game Institute.',
        confidence: 0.78,
        tags: ['World Game', 'global design', 'education', 'systems thinking'],
        primaryDomain: 'design',
    },
    {
        id: 'ej-applewhite',
        canonicalName: 'E. J. Applewhite',
        alternateNames: ['Edgar J. Applewhite'],
        birthDate: '1918',
        birthDatePrecision: DatePrecision.YEAR,
        deathDate: '2005',
        deathDatePrecision: DatePrecision.YEAR,
        gender: 'Male',
        nationalities: [{ name: 'American' }],
        occupations: [
            { name: 'Author', domain: 'writing' },
            { name: 'CIA Officer', domain: 'policy' },
        ],
        bioSummary: 'Edgar J. Applewhite was an American author and former CIA officer who became Fuller\'s chief literary collaborator. He co-authored "Synergetics" (1975) and "Synergetics 2" (1979) with Fuller, helping to organize and elucidate Fuller\'s complex geometric philosophy.',
        confidence: 0.80,
        tags: ['Synergetics', 'writing', 'collaboration'],
        primaryDomain: 'writing',
    },
    {
        id: 'jaime-snyder',
        canonicalName: 'Jaime Snyder',
        birthDate: '1958',
        birthDatePrecision: DatePrecision.YEAR,
        gender: 'Male',
        nationalities: [{ name: 'American' }],
        occupations: [
            { name: 'Designer', domain: 'design' },
            { name: 'Archivist', domain: 'education' },
        ],
        affiliations: [
            { name: 'Buckminster Fuller Institute', role: 'Board Member' },
        ],
        bioSummary: 'Jaime Snyder is the grandson of R. Buckminster Fuller and a designer and archivist who has worked to preserve and extend his grandfather\'s legacy. He has been active in making Fuller\'s archives accessible and interpreting his ideas for contemporary audiences.',
        confidence: 0.75,
        tags: ['family', 'archives', 'legacy'],
        primaryDomain: 'family',
    },
    {
        id: 'amy-edmondson',
        canonicalName: 'Amy Edmondson',
        birthDate: '1959',
        birthDatePrecision: DatePrecision.YEAR,
        gender: 'Female',
        nationalities: [{ name: 'American' }],
        occupations: [
            { name: 'Professor', domain: 'education' },
            { name: 'Author', domain: 'writing' },
        ],
        affiliations: [
            { name: 'Harvard Business School', role: 'Novartis Professor of Leadership', start: '1996' },
        ],
        bioSummary: 'Amy C. Edmondson is an American scholar of leadership and management at Harvard Business School. Early in her career she worked as Fuller\'s chief engineer on geodesic dome projects and wrote "A Fuller Explanation" (1987), one of the most accessible introductions to Fuller\'s synergetics.',
        wikidataId: 'Q4749433',
        confidence: 0.85,
        tags: ['synergetics', 'leadership', 'Harvard', 'geodesic dome'],
        primaryDomain: 'education',
    },
    {
        id: 'paul-ehrlich',
        canonicalName: 'Paul Ehrlich',
        alternateNames: ['Paul R. Ehrlich'],
        birthDate: '1932-05-29',
        birthDatePrecision: DatePrecision.DAY,
        birthPlace: { city: 'Philadelphia', region: 'Pennsylvania', country: 'USA' },
        gender: 'Male',
        nationalities: [{ name: 'American' }],
        occupations: [
            { name: 'Biologist', domain: 'ecology' },
            { name: 'Professor', domain: 'education' },
            { name: 'Author', domain: 'writing' },
        ],
        affiliations: [
            { name: 'Stanford University', role: 'Bing Professor of Population Studies', start: '1966' },
        ],
        bioSummary: 'Paul R. Ehrlich is an American biologist and educator known for his work on population biology and ecology. Author of "The Population Bomb" (1968), he corresponded with Fuller on questions of global resource allocation, sustainability, and the carrying capacity of "Spaceship Earth."',
        wikidataId: 'Q352858',
        wikipediaSlug: 'Paul_R._Ehrlich',
        confidence: 0.88,
        tags: ['ecology', 'population', 'Stanford', 'sustainability'],
        primaryDomain: 'ecology',
    },
];
